version: "3.9"

services:
  backend:
    build: ./backend

    ports:
      - "8080:8080"

    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      DATABASE_URL: postgresql://

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
